import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

live_config_reload: true

window:
  opacity: 0.95
  padding:
    x: 10
    y: 10
  dynamic_padding: false
  decorations: none
  dimensions:
    columns: 120
    lines: 36

font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  size: 12
