live_config_reload: true

window:
  opacity: 0.95
  padding:
    x: 16
    y: 16
  dynamic_padding: false
  decorations: full
  dimensions:
    columns: 120
    lines: 36

font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  size: 10.0
