
[font]
size = 12

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.95

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 10
y = 10

[general]

live_config_reload = true
