
[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5

[general]
import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true
