
[font]
size = 12

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 5
y = 5

[general]

live_config_reload = true
