import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

live_config_reload = true

[font]
size = 14

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.95

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 10
y = 10
