export GOBIN="$HOME/go/bin"
export PATH="$PATH:/snap/bin:/usr/local/go/bin:$GOBIN"
export PAGER=""

# ---- History config ----
HISTFILE="$HOME/.zsh_history"  # where to save history
HISTSIZE=100000                # how many commands to keep in memory
SAVEHIST=100000                # how many commands to save to $HISTFILE

setopt APPEND_HISTORY          # append rather than overwrite the history file
setopt INC_APPEND_HISTORY      # write to history file as commands are entered
setopt SHARE_HISTORY           # share history across all zsh sessions
setopt HIST_IGNORE_ALL_DUPS    # don't record duplicates
setopt HIST_REDUCE_BLANKS      # trim extra spaces

### CUSTOM CONFIGURATION

autoload -Uz compinit
compinit
zmodload zsh/complist
zstyle ':completion:*' menu select

compdef eza=ls

export EDITOR=nvim
export VISUAL=nvim
export BROWSER="brave"

if [[ -z "$DISPLAY" ]] && [[ "$(tty)" == "/dev/tty1" ]]; then
    exec startx &>/dev/null
fi

alias myip="curl http://ipecho.net/plain; echo"
alias grep='grep --color=auto'
alias src='source ~/.zshrc'
alias ls='eza --color=always --icons'
alias ll='eza -lah --color=always --icons'
alias l='ll;'
alias b='cd ..'
alias f='cd -'
alias ram='free -h'
alias random='openssl rand -base64 48'
alias off='sudo shutdown -h now'
alias size='dust'
alias failed='sudo systemctl --failed'
alias his='history | grep '
alias fs='sudo \df -h /'
alias jrn='sudo journalctl -p 3 -xb'
alias vim='nvim'
alias vi='nvim'
alias v='nvim'
alias cl='clear'
alias remove_orphans='pacman -Qtdq | sudo pacman -Rns'
alias clear_logs='sudo rm -rf /var/log/journal/*'
alias desk='cd ~/Desktop/'
alias doc='cd ~/Documents/'
alias down='cd ~/Downloads/'
alias proj='cd ~/Projects/'
alias wtr='curl wttr.in/Burgas'
alias vc='nvim ~/.config/nvim/'
alias temp='sensors'
alias reboot='sudo shutdown -r now'
alias notes='cd ~/Documents/notes && vim'
alias todos='cd ~/Documents/notes && vim todos'
alias slp='sudo systemctl suspend'
alias less='less -S'
alias up='uptime -p'
alias show_zombies="ps aux | grep -E \"Z|defunct\""
alias show_parent_process="ps -o ppid= -p "
alias ff='~/Projects/dotfiles/scripts/ff.sh'
alias tree='eza -T'
alias find='fd'
alias fh='fastfetch'
alias mfa='~/Projects/dotfiles/scripts/mfa.sh'
alias p='~/Projects/dotfiles/scripts/pass'
alias update='yay -Syyu'
alias cat='bat'
alias cal='cal -m'
alias copy='~/Projects/dotfiles/scripts/copy.sh'
alias g='git'
alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
compdef g=git

#########
# vi mode
#########
bindkey -v

# Vim-like navigation when doing tab-complete
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

bindkey -M viins '^Q' push-line-or-edit
bindkey -M vicmd '^Q' push-line-or-edit

# switch to command mode with jj
bindkey '^j' vi-cmd-mode

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# incremental search in insert mode
bindkey "^F" history-incremental-search-forward
bindkey "^R" history-incremental-search-backward

# beginning search with arrow keys and j/k
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search

# beginning search in insert mode, redundant with the up/down arrows above
# but a little easier to press.
bindkey "^P" history-search-backward
bindkey "^N" history-search-forward

# incremental search in vi command mode
bindkey -M vicmd '?' history-incremental-search-backward
bindkey -M vicmd '/' history-incremental-search-forward

# navigate matches in incremental search
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward

# zsh-autosuggestion accept
bindkey '^E' autosuggest-accept

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
