vim.cmd('abb _td // TODO:')
vim.cmd('abb _fx // FIX:')
vim.cmd('abb _hk // HACK:')
vim.cmd('abb _wrn // WARNING:')
vim.cmd('abb _prf // PERFORMANCE:')
vim.cmd('abb _nt // NOTE:')
vim.cmd('abb _tst // TEST:')
