require('plugins_configs/telescope')
require('plugins_configs/treesitter')
require('plugins_configs/harpoon')
require('plugins_configs/undotree')
require('plugins_configs/gitsigns')
require('plugins_configs/lsp')
require('plugins_configs/cmp') -- this has to be after the lsp config
require('plugins_configs/lualine')
require('plugins_configs/barbar')
require('plugins_configs/tree')
