require('plugins_configs/telescope')
require('plugins_configs/treesitter')
require('plugins_configs/harpoon')
require('plugins_configs/lsp')
require('plugins_configs/lualine')
require('plugins_configs/tree')
require('plugins_configs/dap')
require('plugins_configs/gitsigns')
