#!/bin/bash
# Taken from https://gist.github.com/csivanich/10914698

CURRENT_LANGUAGE=$(setxkbmap -query | grep -i layout | awk '{print $2}' | cut -d\, -f1)
if [[ $CURRENT_LANGUAGE != "us" ]]
then
    ~/Projects/dotfiles/scripts/keyboard.sh
fi

IMAGE=/tmp/i3lock.png
SCREENSHOT="scrot -z $IMAGE"
BLURTYPE="0x5"

$SCREENSHOT
convert $IMAGE -blur $BLURTYPE $IMAGE
i3lock -i $IMAGE -f
rm $IMAGE
