#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu -h 29 -c -i -l 10 -bw 3 -fn "UbuntuMono Nerd Font Mono:size=12" -nb "#222222" -nf "#bbbbbb" -sb "#005577" -sf "#eeeeee" "$@")

[[ -n $password ]] || exit

gpg_cache=$(gpg-connect-agent 'keyinfo --list' /bye 2>/dev/null | awk 'BEGIN{CACHED=0} /^S/ {if($7==1){CACHED=1}}   END{if($0!=""){print CACHED} else {print "none"}}')

if [[ $gpg_cache == 1 ]]; then
    pass show -c "$password" 2 >/dev/null
else
    st -e pass show -c "$password" 2 >/dev/null
fi

