require('config.lsp')
require('config.plugins.theme')
require('config.plugins.telescope')
require('config.plugins.lualine')
require('config.plugins.tree')
require('config.plugins.gitsigns')
require('config.plugins.autopairs')
require('config.plugins.codecompanion')
